# Generated by Django 2.2.1 on 2019-06-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='konu',
            field=models.TextField(default='genel'),
            preserve_default=False,
        ),
    ]
